from PySide6.QtCore import QCoreApplication


def translation_sources():
    # WeatherResourceManager 上下文的所有字符串
    QCoreApplication.translate("WeatherResourceManager", "Sunny")
    QCoreApplication.translate("WeatherResourceManager", "Clear")
    QCoreApplication.translate("WeatherResourceManager", "Mainly Sunny")
    QCoreApplication.translate("WeatherResourceManager", "Mainly Clear")
    QCoreApplication.translate("WeatherResourceManager", "Partly Cloudy")
    QCoreApplication.translate("WeatherResourceManager", "Cloudy")
    QCoreApplication.translate("WeatherResourceManager", "Foggy")
    QCoreApplication.translate("WeatherResourceManager", "Rime Fog")
    QCoreApplication.translate("WeatherResourceManager", "Light Drizzle")
    QCoreApplication.translate("WeatherResourceManager", "Drizzle")
    QCoreApplication.translate("WeatherResourceManager", "Heavy Drizzle")
    QCoreApplication.translate("WeatherResourceManager", "Light Freezing Drizzle")
    QCoreApplication.translate("WeatherResourceManager", "Freezing Drizzle")
    QCoreApplication.translate("WeatherResourceManager", "Light Rain")
    QCoreApplication.translate("WeatherResourceManager", "Rain")
    QCoreApplication.translate("WeatherResourceManager", "Heavy Rain")
    QCoreApplication.translate("WeatherResourceManager", "Light Freezing Rain")
    QCoreApplication.translate("WeatherResourceManager", "Freezing Rain")
    QCoreApplication.translate("WeatherResourceManager", "Light Snow")
    QCoreApplication.translate("WeatherResourceManager", "Snow")
    QCoreApplication.translate("WeatherResourceManager", "Heavy Snow")
    QCoreApplication.translate("WeatherResourceManager", "Snow Grains")
    QCoreApplication.translate("WeatherResourceManager", "Light Showers")
    QCoreApplication.translate("WeatherResourceManager", "Showers")
    QCoreApplication.translate("WeatherResourceManager", "Heavy Showers")
    QCoreApplication.translate("WeatherResourceManager", "Light Snow Showers")
    QCoreApplication.translate("WeatherResourceManager", "Snow Showers")
    QCoreApplication.translate("WeatherResourceManager", "Thunderstorm")
    QCoreApplication.translate("WeatherResourceManager", "Light Thunderstorms With Hail")
    QCoreApplication.translate("WeatherResourceManager", "Thunderstorm With Hail")
